name: CI-CD with Docker Hub

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vehicle-insurance:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/vehicle-insurance:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Pull and run the Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/vehicle-insurance:latest
          docker stop vehicle-insurance || true
          docker rm vehicle-insurance || true
          docker run -d -p 5000:5000 --name vehicle-insurance ${{ secrets.DOCKER_USERNAME }}/vehicle-insurance:latest
